name: car_wash_app
description: Car Wash Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+12


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  flutter_search_panel: ^1.0.1
  generic_bloc_provider: ^1.0.9
  equatable: ^0.6.1
  meta: ^1.1.7
  shared_preferences: ^0.5.4+1
  flutter_multiselect: ^0.4.0
  datetime_picker_formfield: ^1.0.0
  flutter_sms: ^1.1.0
  flutter_open_whatsapp: ^0.1.2
  url_launcher: ^5.4.2
  permission_handler: ^4.3.0
  file_utils: ^0.1.4
  fluttertoast: ^7.1.6
  excel: ^1.1.5

  #firebase
  firebase_auth:
  google_sign_in:
  firebase_storage: ^3.0.6
  cloud_firestore: ^0.12.9+4
  flutter_facebook_login: ^3.0.0
  firebase_core:

  #nemu
  popup_menu: ^1.0.3

  #images
  carousel_slider: ^1.3.1
  flutter_image_compress: ^0.7.0
  image_cropper: ^1.1.0
  image_picker: ^0.6.7+22
  image: ^2.1.4
  image_picker_saver: ^0.3.0
  screenshot: ^0.1.1
  path_provider: ^1.6.28
  photo_view: ^0.9.2
  image_gallery_saver: ^1.6.7

  #charts
  syncfusion_flutter_charts: ^18.2.55

  #Conectivity
  connectivity: ^0.4.6+2

  #alerts-dialogs
  rflutter_alert: ^1.0.3

  #number formatter
  intl: ^0.16.0

  #email
  mailer: ^3.2.1

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

#dependency_overrides:
#  image: '2.1.12'

dev_dependencies:
  #se comentan estas lineas para que funcione la libreria image: ^2.1.10
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/images/logo-car-wash-launcher.png"
  #image_path_android: "assets/images/icon-710x599-android.png"
  #image_path_ios: "assets/images/icon-710x599-ios.png"
  android: "launcher_icon" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/car_wash_movil_logo_blanco.png
    - assets/images/icon_facebook.png
    - assets/images/icon_google.png
    - assets/images/car_wash_movil_logo_color.png
    - assets/images/img_landing.png
    - assets/images/profile21.jpg
    - assets/images/icon_nueva_factura.png
    - assets/images/icon_facturas.png
    - assets/images/icon_informes.png
    - assets/images/icon_home.png
    - assets/images/icon_admin.png
    - assets/images/icon_car_admin.png
    - assets/images/icon_car.png
    - assets/images/icon_motorcycle.png
    - assets/images/icon_motorcycle_admin.png
    - assets/images/icon_suv_car_admin.png
    - assets/images/icon_suv_car.png
    - assets/images/icon_logout.png
    - assets/images/icon_nueva_factura_white.png
    - assets/images/background_ph_image.png
    - assets/images/icon_facturas_blanco.png
    - assets/images/profile_placeholder.png
    - assets/images/icon_filter.png
    - assets/images/icon_filter1.png
    - assets/images/logo-car-wash.png
    - assets/images/factura-impr-2.png
    - assets/images/logo-car-wash-launcher.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Light.ttf
    - family: Avenir Next
      fonts:
        - asset: fonts/AvenirNext-Bold.ttf
        - asset: fonts/AvenirNext-DemiBold.ttf
        - asset: fonts/AvenirNext-Heavy.ttf
        - asset: fonts/AvenirNext-Medium.ttf
        - asset: fonts/AvenirNext-Regular.ttf

