// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQX23yFRApxVA1G8UM1BbxsPfYjHEHd4',
    appId: '1:282309180715:android:3a5bcea6ab58447ed4d96e',
    messagingSenderId: '282309180715',
    projectId: 'carwash-app-9a2c2',
    databaseURL: 'https://carwash-app-9a2c2.firebaseio.com',
    storageBucket: 'carwash-app-9a2c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCo-NzjRacsaky1oi5pj7uHh6P4Q6fey0',
    appId: '1:282309180715:ios:9c7628ab76acf24ad4d96e',
    messagingSenderId: '282309180715',
    projectId: 'carwash-app-9a2c2',
    databaseURL: 'https://carwash-app-9a2c2.firebaseio.com',
    storageBucket: 'carwash-app-9a2c2.appspot.com',
    androidClientId: '282309180715-jg09eab63uvstjc21draa7qscd3amv45.apps.googleusercontent.com',
    iosClientId: '282309180715-4fabauqr5j5im5t5bjqoq5l3kp11okjs.apps.googleusercontent.com',
    iosBundleId: 'com.carwashmovil.carWashApp',
  );
}
